/**
 * U.S. Supreme Court Justice Data
 * Current composition as of November 2025
 * Photos sourced from Wikimedia Commons (official SCOTUS portraits)
 */

export const SUPREME_COURT_JUSTICES = [
  {
    name: "John G. Roberts Jr.",
    title: "Chief Justice",
    appointedBy: "George W. Bush",
    party: "Republican",
    confirmed: "September 29, 2005",
    birthdate: "January 27, 1955",
    imageUrl: "/assets/john_roberts.jpg",
    signatureUrl: "/assets/John_Roberts_signature.png",
  },
  {
    name: "Clarence Thomas",
    title: "Associate Justice",
    appointedBy: "George H.W. Bush",
    party: "Republican",
    confirmed: "October 23, 1991",
    birthdate: "June 23, 1948",
    imageUrl: "/assets/clarence_thomas.jpg",
    signatureUrl: "/assets/Clarence_Thomas'_signature.png",
  },
  {
    name: "Samuel A. Alito Jr.",
    title: "Associate Justice",
    appointedBy: "George W. Bush",
    party: "Republican",
    confirmed: "January 31, 2006",
    birthdate: "April 1, 1950",
    imageUrl: "/assets/samuel_alito.jpg",
    signatureUrl: "/assets/Samuel_Alito_signature.png",
  },
  {
    name: "Sonia Sotomayor",
    title: "Associate Justice",
    appointedBy: "Barack Obama",
    party: "Democrat",
    confirmed: "August 8, 2009",
    birthdate: "June 25, 1954",
    imageUrl: "/assets/sonia_sotomayor.jpg",
    signatureUrl: "/assets/SotomayorSig.png",
  },
  {
    name: "Elena Kagan",
    title: "Associate Justice",
    appointedBy: "Barack Obama",
    party: "Democrat",
    confirmed: "August 7, 2010",
    birthdate: "April 28, 1960",
    imageUrl: "/assets/elena_kagan.jpg",
    signatureUrl: "/assets/Elena_Kagan_signature.svg",
  },
  {
    name: "Neil M. Gorsuch",
    title: "Associate Justice",
    appointedBy: "Donald Trump",
    party: "Republican",
    confirmed: "April 10, 2017",
    birthdate: "August 29, 1967",
    imageUrl: "/assets/neil_gorsuch.jpg",
    signatureUrl: "/assets/Neil_Gorsuch_signature.png",
  },
  {
    name: "Brett M. Kavanaugh",
    title: "Associate Justice",
    appointedBy: "Donald Trump",
    party: "Republican",
    confirmed: "October 6, 2018",
    birthdate: "February 12, 1965",
    imageUrl: "/assets/brett_kavanaugh.jpg",
    signatureUrl: "/assets/Brett_Kavanaugh_signature.png",
  },
  {
    name: "Amy Coney Barrett",
    title: "Associate Justice",
    appointedBy: "Donald Trump",
    party: "Republican",
    confirmed: "October 27, 2020",
    birthdate: "January 28, 1972",
    imageUrl: "/assets/amy_coney_barrett.jpg",
    signatureUrl: "/assets/AmyConeyBarrettSignature.png",
  },
  {
    name: "Ketanji Brown Jackson",
    title: "Associate Justice",
    appointedBy: "Joe Biden",
    party: "Democrat",
    confirmed: "April 7, 2022",
    birthdate: "September 14, 1970",
    imageUrl: "/assets/ketanji_brown_jackson.jpg",
    signatureUrl: "/assets/Ketanji_Brown_Jackson_signature.png",
  },
];
